# Generated by Django 4.1.2 on 2023-01-16 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_brand'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
