# Generated by Django 4.1.2 on 2023-01-09 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_remove_order_payment_remove_orderproduct_payment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
