# Generated by Django 4.1.2 on 2023-01-11 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0003_remove_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Order_day',
            field=models.IntegerField(default=11),
        ),
        migrations.AddField(
            model_name='order',
            name='Order_month',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='order',
            name='Order_year',
            field=models.IntegerField(default=2023),
        ),
    ]
