# Generated by Django 4.1.2 on 2023-01-16 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0006_alter_order_order_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Order_day',
            field=models.IntegerField(default=16),
        ),
    ]
