# Generated by Django 4.1.2 on 2023-01-18 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0008_rename_created_at_order_order_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_date',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='order',
            name='Order_day',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='order',
            name='Order_month',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='order',
            name='Order_year',
            field=models.IntegerField(default=2023),
        ),
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
